title: "wellcome to Emily's home"
description: >-
  一个90后的数字遗产.
show_downloads: true
google_analytics:
remote_theme: jekyll-theme-modernist
github_username: shmilyxiaoqin
plugins:
  - jekyll-feed
  - jekyll-seo-tag

---

---

